In [31]:
import pandas as pd
dat=pd.read_csv("file.csv")
dat

,tracking_id,gene_id,gene_short_name,tss_id,locus,fiBat1,fiBat2,fiBat3,fiBat4,Ome1,Ome2,Ome3,Sub1,Sub2,Sub3
0,ENSG00000228150,ENSG00000228150,RP11-84A14.4,TSS132524,chr1:10002980-10010032,0.000000,0.100232,0.098904,0.000000,1.27912,0.000000,0.00000,0.157296,1.07027,0.000000
1,ENSG00000173614,ENSG00000173614,NMNAT1,"TSS114535,TSS114536,TSS125200,TSS6693",chr1:10003485-10045559,6.055920,6.513520,5.967810,4.973360,4.90415,0.936242,1.16901,4.126180,5.71057,4.962680
2,ENSG00000202415,ENSG00000202415,RN7SKP269,TSS63399,chr1:10007375-10007694,0.000000,0.000000,0.183589,0.618655,0.00000,0.000000,0.00000,0.000000,0.00000,0.335925
3,ENSG00000099260,ENSG00000099260,PALMD,"TSS120541,TSS124355,TSS3519,TSS92880",chr1:100111498-100160097,48.318300,46.010800,45.757600,36.601800,67.81640,66.762800,53.84760,178.578000,166.51500,142.468000
4,ENSG00000223656,ENSG00000223656,HMGB3P10,TSS71526,chr1:100163797-100164734,0.067475,0.326483,0.588133,0.207621,3.63796,1.637090,0.00000,4.310350,1.02712,2.627780
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57849,ENSG00000225685,ENSG00000225685,TSPY5P,"TSS184156,TSS72598",chrY:9904162-9906760,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.00000,0.000000
57850,ENSG00000235193,ENSG00000235193,AC006987.4,TSS129769,chrY:9925634-9927195,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.00000,0.000000
57851,ENSG00000251766,ENSG00000251766,RNA5SP518,TSS153987,chrY:9928018-9928137,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.00000,0.000000
57852,ENSG00000235691,ENSG00000235691,AC006987.5,TSS111181,chrY:9928410-9928816,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.00000,0.000000
57853,ENSG00000252289,ENSG00000252289,RNA5SP519,TSS653,chrY:9930483-9930602,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.00000,0.000000

In [45]:
filt_dat = dat[dat["fiBat1"]!=0]
filt_dat_1 = filt_dat[filt_dat["fiBat2"]!=0]
filt_dat_2 = filt_dat_1[filt_dat_1["fiBat3"]!=0]
filt_dat_3 = filt_dat_2[filt_dat_2["fiBat4"]!=0]
filt_dat_4 = filt_dat_3[filt_dat_3["Ome1"]!=0]
filt_dat_5 = filt_dat_4[filt_dat_4["Ome2"]!=0]
filt_dat_6 = filt_dat_5[filt_dat_5["Ome3"]!=0]
filt_dat_7 = filt_dat_6[filt_dat_6["Sub1"]!=0]
filt_dat_8 = filt_dat_7[filt_dat_7["Sub2"]!=0]
filt_dat_9 = filt_dat_8[filt_dat_8["Sub3"]!=0]
len(filt_dat_9)

filt_dat_9.to_csv('new.csv')
#filt_dat_9.to_csv('C:\Users\eguni\OneDrive\Desktop\new.csv')

#filt_dat_9.to_excel()